#!/bin/bash

echo "Starting Linux upgrades..."
sudo apt-get update
echo "Apt-get update resolved"
sudo apt-get upgrade
echo "Apt-get upgrade finished successfully"
sudo npm install -g npm
echo "NPM updated successfully. Heading over to Ghost..."
cd ../../../var/www/ghost
echo "Navigated successfully to Ghost directory"
sudo npm install -g ghost-cli@latest
echo "Installed latest Ghost-cli version"
ghost update
echo "Santeri's automatic script finished. Server maintenance complete."
